name: Run Tests on PR to dev

on:
  pull_request:
    branches:
      - dev

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest
